files:
- TrussModel.py
- TrussParams.py
id: quo-02
synopsis: This example illustrates how quoFEM interacts with OpenSeesPy. A simple
  forward propagation procedure is run to estimate the first and second central moments
  of a FE model's response, given the marginal distributions of various random parameters.
title: Forward Propagation - OpenSeesPy
